# Generated by Django 4.1.6 on 2024-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_read_by_alter_message_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="read_by",),
        migrations.AddField(
            model_name="message", name="read", field=models.BooleanField(default=False),
        ),
    ]
