# Generated by Django 4.2.10 on 2024-03-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_message_read_by_message_read"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="slug",),
    ]
